### PR TITLE
feat: increase boost for main fields

### LINKED ISSUE #155: Augmenter le boost pour la dénomination de l'entreprise
Aujourd'hui, le fait qu'on attribue le score basé sur le facteur du nombre d'établissements ouvert pose un problème. Certaines entreprises qui ont les termes de la recherche dans la dénomination sont relégués à des rangs inférieurs par rapport à d'autres entreprises qui ont les termes dans des champs secondaires (enseigne, adresse par exemple) mais qui ont un nombre d'établissements plus élevés.

Exemple quand on cherche `blomet` c'est la ville de Paris qui ressort en premier (car elle a un établissements à cette adresse) mais pas l'entreprise `hoteliere blomet` qui pourtant contient les termes dans sa dénomination (elle est reléguée à la 2e place). 

En augmentant le boost, on permet de rééquilibrer l'ordre.

### PR DESCRIPTION
**Pull request by geoffreyaldebert**
To resolve #155

### CODE REVIEW

**Comment by geoffreyaldebert** [comment]
boost values and multiplier factor are calculated with an extreme and robust data science model call "trust me, ok?"

**Comment by HAEKADI** [comment]
The purpose of this PR is to give more weight to the `denomination` fields in the search algorithm without degrading its performance.
 
This PR:
 * boosts `nom_complet` field using a high score (1000) multiplier function
 * adds a query that match exactly the `sigle` field with a mid-range (10) multiplier function
 * adds a multi-match query that searches through all `denomination` fields including `denomination_usuelle[1,2,3]`, which uses the same mid-range multiplier (10)
 * uses a a multiplier score function with the lowest score boost (1) for `etablissements` nested search query
 * formats the `nom_complet` field included in the API payload using the following formula :
  `denomination de l'unité légale | Nom et prénom | Nom inconnu (denomination usuelle) (sigle de l'unité légale)`
* adds `sigle` field to the API payload

This updated version of the search query gave place to the following relevance scores:
* In terms of our control dataset (siren labeled logs):
Screenshot 2023-02-14 at 20 57 56
* For the siret (restaurant) dataset, we tested for both siren and siren relevance:
Screenshot 2023-02-16 at 11 55 31
Screenshot 2023-02-16 at 11 56 00

Overall the updated version performs better with the control siren dataset. 
This improvement is not particularly significant in the siren dataset. Which is not entirely problematic, since our aim is to mostly avoid performance degradation on these datasets since they are not representative of the our overall use cases.
This update shows its strength on specific cases which are not included in the test dataset.


@geoffreyaldebert if you could please add a lit of the cases we discussed for keepsake.

**Review by HAEKADI — APPROVED** [review]
🚀🚀🚀

**Comment by geoffreyaldebert** [comment]
👏

**Comment by HAEKADI** [comment]
closes #174

**Pull request merged**
